[package]
name = "ts2graph_rs"
version = "0.1.0"
edition = "2024"

[lib]
name = "ts2graph_rs"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.25", features = ["extension-module"] }
ndarray = "0.15"
numpy = "0.25"
tch = { version = "0.18.1", features = ["cpython"] }
