# @package _global_

defaults:
  - dataset: metr_la
  - _self_

dataset:
  missingness:
    enabled: true
    pattern: mcar_blocks
    target_rate: 0.1244 # Default value (will be overridden sweeper)
    block_size: 0.001
    first_rate: 0.1244

hydra:
  sweeper:
    params:
      dataset.missingness.target_rate: 0.1244, 0.3, 0.5, 0.7
