name: dtw
input_kind: series

series_fraction: 0.01
missing_value_restrictions: "full"
missing_value_adjustment: "proportion_of_missing_values"

cache_dir: ./graphs_transformations/cache/
scenario_key: null
