defaults:
  # - experiment: baseline
  - dataset: airq_small
  - model: stgi
  - training: default
  - graph: ed_rbf_topk
  - _self_

seed: 42
graph_stats: false
mode: s
use_spatial: true
use_temporal: false
task: true

paths:
  suffix: ${cond:${eq:${dataset.missingness.pattern}, aligned_blocks}, cov${dataset.missingness.sensor_coverage_levels.0}, rate${dataset.missingness.target_rates}}
  root: ./experiments/results
  save_path: ${paths.root}/${model.name}/${graph.name}/${dataset.name}/${cond:${dataset.missingness.enabled}, missing_${dataset.missingness.pattern}, default}/ln${model.layer_num}/${model.layer_type}/${now:%Y%m%d}/
  file_name: ${now:%Y%m%d_%H%M%S}_${model.name}_${dataset.name}_${mode}_${graph.label}_${paths.suffix}, ''}.json

hydra:
  job:
    chdir: false
