defaults:
  - distance: masked_euclidean
  - affinity: gaussian_kernel
  - sparsifier: topk
  - _self_

name: ed_rbf_topk

# Sparsifier setting
sparsifier:
  param:
    mode: fraction
    value: ???

label:
